import './globals.css';
import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import NextThemeProvider from '~/components/theme';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    // https://reactjs.org/docs/dom-elements.html#suppresshydrationwarning:~:text=It%20only%20works%20one%20level%20deep
    <html lang="en" suppressHydrationWarning>
      <body className={`${montserrat.className} overflow-x-hidden bg-gray-50 dark:bg-gray-950 dark:text-white`}>
        <NextThemeProvider>{children}</NextThemeProvider>
      </body>
    </html>
  );
}
